### ISSUE TITLE
考虑支持 webGL2.0  方便编译 wasm for web 版本么

### ISSUE THREAD

**Issue by helloyokoy** [RuiwenTang/Skity#20]
考虑支持 webGL2.0  方便编译 wasm for web 版本么

**Comment by RuiwenTang** [comment]
@helloyokoy 我不是很了解wasm，不过这倒是个好想法，我可以去研究一下。当然也欢迎提PR哈

**Comment by helloyokoy** [comment]
@RuiwenTang   我用 emscripten 已经编译你的代码，改了一部分，已经编译通过了，但是在 web 画矢量还是画不出来，Chrome上报了一堆的 opengl shader 的错误，webgl 2.0 对应的是  opengl es3.0 ，应该是 glsl 脚本里面用了  webgl不支持的属性 到时不能正确绘制。

**Comment by RuiwenTang** [comment]
@helloyokoy 可以看到具体是什么错误么，现在shader的`header`部分是用宏判断的，可能没考虑WebGL的情况

**Comment by RuiwenTang** [comment]
增加了一个简单的webgl example，可以看下 experiment/webgl 目录中的例子
