### ISSUE TITLE
onDrawRect stroke颜色不对

### ISSUE THREAD

**Issue by 0TemetNosce0** [RuiwenTang/Skity#23]
393行的stroke:
auto draw = GenerateColorOp(work_paint, false, raster.RasterBounds());
应该是auto draw = GenerateColorOp(work_paint, true, raster.RasterBounds());

**Comment by RuiwenTang** [comment]
@0TemetNosce0 额，确实有问题，如果Paint使用 StrokeAndFill绘制，颜色会使用Fill的颜色
