### ISSUE TITLE
曲线绘制不光滑

### ISSUE THREAD

**Issue by 0TemetNosce0** [RuiwenTang/Skity#27]
```
  skity::Path path;
  path.moveTo(10, 10);
  path.quadTo(256, 64, 128, 128);
  path.quadTo(10, 192, 250, 250);
  canvas->drawPath(path, paint);
```

**Comment by 0TemetNosce0** [comment]
![](https://github.com/0TemetNosce0/pic/blob/master/QQ%E6%88%AA%E5%9B%BE20220426160015.png?raw=true)

**Comment by RuiwenTang** [comment]
![screenshot-20220426-191920](https://user-images.githubusercontent.com/26308154/165300951-da71d82d-217b-4ab2-9511-ee46e63b1bc3.png)

同步一下最新的代码，提高了曲线近似的精度

**Comment by tuzhong007** [comment]
Why do I still have this problem on 2023/3/20, isn't it resolved?

**Comment by tuzhong007** [comment]
@RuiwenTang After I commented out some codes in hw_path_visitor.cc, the effect of quadratic curve is finally smooth. The following code is what I commented out. It seems the `OnQuadTo` function is inaccurate.
![image](https://user-images.githubusercontent.com/52589659/227446083-5990c722-87bb-44e4-9096-5d896215a19c.png)

**Comment by RuiwenTang** [comment]
You can disable geometry shader by return false in `GLCanvas::SupportGeometryShader` to work around it

**Comment by tuzhong007** [comment]
@RuiwenTang  It seems in the geometry shader case, your code just split the curve into 16 pieces, so when I scale the canvas a little bit, this issue still exist.
![image](https://user-images.githubusercontent.com/52589659/228855508-5721b773-fd05-43cb-b7fd-d66750e66701.png)
But after I turned off the geometry shader, the effect is smooth.

**Comment by RuiwenTang** [comment]
> @RuiwenTang It seems in the geometry shader case, your code just split the curve into 16 pieces, so when I scale the canvas a little bit, this issue still exist. ![image](https://user-images.githubusercontent.com/52589659/228855508-5721b773-fd05-43cb-b7fd-d66750e66701.png) But after I turned off the geometry shader, the effect is smooth.

Maybe that's why skia split curve into 32 line segments.......

**Comment by tuzhong007** [comment]
@RuiwenTang  I noticed that you included [GPU-accelerated Path Rendering](https://github.com/RuiwenTang/Skity/blob/main/resources/gpupathrender.pdf) as reference, but I am not sure where did you use the algorithms in this thesis. Could you please let me know where in the project you used it? I'd love to take a closer look and learn more about how you applied it. Thank you!

**Comment by RuiwenTang** [comment]
@tuzhong007 I used the paper's formular to handle curve when I just started writing Skity, and I saved this implementation in this tag [legacy_impl](https://github.com/RuiwenTang/Skity/blob/cf145bb50f7bd3995da74da82a732c08986e2ac7/shaders/fs_stencil_basic.glsl).
But I found call discard in fragment shader may cause some performance issue, so I use Geometry Shader or break curve in CPU.
